version: '3.7'

services:
  app:
    container_name: cry_goapp
    build: .
    volumes:
      - user_data:/data
    ports:
      - 1323:1323
    secrets:
      - source: server_config
        target: config.yml
    command: -config="config"
    networks:
      - app_net
    depends_on:
      - mongo
      - celery
  mongo:
    container_name: cry_mongo
    image: mongo:latest
    #volumes:
    # - ./mongo_data:/data
    networks:
      app_net:
        aliases:
            - cry_mongo
  redis:
    container_name: cry_redis
    image: redis:latest
    networks:
      - app_net
  celery:
    container_name: cry_celery
    build:
      context: ./containers
      dockerfile: celery.dockerfile
    volumes:
      - user_data:/data
    environment:
      CELERY_TASK_SERIALIZER: 'json'
      CELERY_ACCEPT_CONTENT: 'json'
      CELERY_RESULT_SERIALIZER: 'json'
      CELERY_ENABLE_UTC: 'True'
      CELERY_TASK_PROTOCOL: 1
    networks:
      - app_net
    depends_on:
      - redis

secrets:
  server_config:
    file: ./config.yml

networks:
  app_net:

volumes:
  user_data: